Name:           ros-melodic-h264-video-encoder
Version:        1.1.3
Release:        1%{?dist}
Summary:        ROS h264_video_encoder package

Group:          Development/Libraries
License:        LGPLv2.1
URL:            http://wiki.ros.org/h264_video_encoder
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-aws-ros1-common
Requires:       ros-melodic-image-transport
Requires:       ros-melodic-image-transport-plugins
Requires:       ros-melodic-kinesis-video-msgs
Requires:       ros-melodic-message-runtime
Requires:       ros-melodic-sensor-msgs
BuildRequires:  gmock-devel
BuildRequires:  gtest-devel
BuildRequires:  ros-melodic-aws-ros1-common
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-h264-encoder-core
BuildRequires:  ros-melodic-image-transport
BuildRequires:  ros-melodic-kinesis-video-msgs
BuildRequires:  ros-melodic-message-generation
BuildRequires:  ros-melodic-rostest
BuildRequires:  ros-melodic-sensor-msgs

%description
ROS1 H264 encoder node

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Thu Aug 01 2019 AWS RoboMaker <ros-contributions@amazon.com> - 1.1.3-1
- Autogenerated by Bloom

* Fri Jun 21 2019 AWS RoboMaker <ros-contributions@amazon.com> - 1.1.2-1
- Autogenerated by Bloom

